repos:
- repo: local
  hooks:
  - id: pytest-check
    stages: [pre-commit]
    types: [python]
    name: pytest-check
    entry: python -m pytest
    language: system
    pass_filenames: false
    always_run: true
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
    language_version: python3
