name: Release from tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: ghalactic/github-release-from-tag@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


  pyinstaller:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

